version: '3'

services:

  client:
    image: nginx:stable-alpine
    ports:
      - 8000:80
    volumes:
      - ./client/index.html:/usr/share/nginx/html/index.html
      - ./client/nginx.conf:/etc/nginx/nginx.conf

  server:
    build:
      context: ./server
    ports:
      - 5000:5000
    volumes:
      - ./uploads:/usr/src/uploads
